# Generated by Django 3.2.2 on 2021-06-10 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=100)),
                ('a_email', models.CharField(max_length=100)),
                ('a_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=100)),
                ('b_category', models.CharField(max_length=100)),
                ('b_author', models.CharField(max_length=100)),
                ('b_user', models.CharField(max_length=100)),
                ('b_price', models.IntegerField()),
                ('b_edition', models.CharField(max_length=100)),
                ('b_image', models.ImageField(default=False, upload_to='images')),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=100)),
                ('u_email', models.CharField(max_length=100)),
                ('u_pass', models.CharField(max_length=100)),
                ('u_add', models.CharField(max_length=100)),
                ('u_city', models.CharField(max_length=100)),
                ('u_contact', models.IntegerField(max_length=12)),
                ('u_book', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.IntegerField(max_length=20)),
                ('b_name', models.CharField(max_length=100)),
                ('b_price', models.IntegerField(max_length=20)),
                ('order_date', models.DateField(null=True)),
                ('total_cost', models.IntegerField(max_length=20)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='bookorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.books')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.cart')),
            ],
            options={
                'db_table': 'bookorder',
            },
        ),
    ]
