# Generated by Django 3.2.2 on 2021-05-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=100)),
                ('a_email', models.CharField(max_length=100)),
                ('a_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=100)),
                ('b_category', models.CharField(max_length=100)),
                ('b_author', models.CharField(max_length=100)),
                ('b_user', models.CharField(max_length=100)),
                ('b_price', models.IntegerField()),
                ('b_edition', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.IntegerField(max_length=20)),
                ('b_name', models.CharField(max_length=100)),
                ('b_price', models.IntegerField(max_length=20)),
                ('total_cost', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=100)),
                ('u_email', models.CharField(max_length=100)),
                ('u_pass', models.CharField(max_length=100)),
                ('u_add', models.CharField(max_length=100)),
                ('u_city', models.CharField(max_length=100)),
                ('u_contact', models.IntegerField(max_length=12)),
                ('u_book', models.CharField(max_length=100)),
            ],
        ),
    ]
