# Generated by Django 3.2.2 on 2021-06-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='b_image',
            field=models.ImageField(default='asdfghjkl', upload_to='images'),
        ),
    ]
