# Generated by Django 3.2.2 on 2021-05-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentt_id', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=20)),
                ('student_surname', models.CharField(max_length=20)),
                ('student_dob', models.DateTimeField()),
                ('student_address', models.CharField(max_length=30)),
                ('student_city', models.CharField(max_length=30)),
                ('student_contact', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
